### ISSUE TITLE
RSMRomania - Graph without active data for the jobs

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/PeViitor_Scrapers_Melania#11]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/rsmromania/index.html
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser

2. Run scraper

3. Check the graph functionality

EXPECTED RESULTS:
The graph must have activ data and show the number of valid jobs

ACTUAL RESULTS:
Graph without active data, doesn't show the number of valid jobs 
![Screenshot_18](https://github.com/peviitor-ro/Scrapers-UI/assets/124587607/f153481c-b98e-4b8f-9894-d061ab5610f2)

**Comment by lalalaurentiu** [comment]
@melania23m if you want this graphic to work, change the file name from RSMRomania_scraper.py to rsmromania_scraper.py.

**Comment by melania23m** [comment]
I changed. Please retest.

**Comment by LarisaM16** [comment]
@melania23m  
![Screenshot_22](https://github.com/peviitor-ro/PeViitor_Scrapers_Melania/assets/124587607/74d83a10-55ae-4b57-aa74-3dfb9329af15)

**Comment by lalalaurentiu** [comment]
@LarisaM16 Fixed!

**Comment by LarisaM16** [comment]
functioneaza!
