### ISSUE TITLE
BDORomania - Graph without active data for the jobs

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/PeViitor_Scrapers_Melania#12]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/bdoromania/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser

2. Run scraper

3. Check the graph functionality

EXPECTED RESULTS:
The graph must have activ data and show the number of valid jobs

ACTUAL RESULTS:
Graph without active data, doesn't show the number of valid jobs
![Screenshot_19](https://github.com/peviitor-ro/Scrapers-UI/assets/124587607/705b8063-64ba-47d3-87d8-87ac9b2996da)

**Comment by lalalaurentiu** [comment]
@melania23m if you want this graphic to work, change the file name from BDORomania_scraper.py to bdoromania_scraper.py.

**Comment by melania23m** [comment]
I  changed. Please retest

**Comment by LarisaM16** [comment]
![Screenshot_21](https://github.com/peviitor-ro/PeViitor_Scrapers_Melania/assets/124587607/2c283606-acb0-43f6-b94c-4855a73de53a)

**Comment by lalalaurentiu** [comment]
@melania23m Fixed graph but your scraper doesn't work
<img width="1440" alt="Screenshot 2023-12-05 at 20 17 13" src="https://github.com/peviitor-ro/PeViitor_Scrapers_Melania/assets/67306273/95fd94c5-66b4-4e0b-a450-5aea05ee6008">
