### ISSUE TITLE
BDORomania

### ISSUE THREAD

**Issue by lalalaurentiu** [peviitor-ro/PeViitor_Scrapers_Melania#2]
Logo not found!
<img width="1440" alt="Screenshot 2023-10-23 at 19 31 53" src="https://github.com/peviitor-ro/PeViitor_Scrapers_Melania/assets/67306273/49771db0-ab9a-4895-a11e-25c762e63ebe">

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/PeViitor_Scrapers_Melania/assets/112417484/5109e285-2bda-40b8-8e9a-20f259037fdb)
fixed! please retest.

**Comment by lalalaurentiu** [comment]
is ok now
