### ISSUE TITLE
BDORomania -for job Auditor junior appear "Bucuresti, Cluj nu este un oras in Romania" instead of " Bucuresti, Cluj "

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/PeViitor_Scrapers_Melania#3]
ENVIRONMENT: PROD
URL: https://firme.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:

1. open URL in the browser
2. type BDORomania in the search bar
3. run scraper
4. check city location for this job `Auditor junior `

EXPECTED RESULTS:
the city is displayed correctly

ACTUAL RESULTS:
city location have "is not a city in Romania" in description

**Comment by LarisaM16** [comment]
![Screenshot_69](https://github.com/peviitor-ro/PeViitor_Scrapers_Melania/assets/124587607/df8be11e-a8dc-4367-be65-dbcb583b8da3)

**Comment by melania23m** [comment]
![image](https://github.com/peviitor-ro/PeViitor_Scrapers_Melania/assets/112417484/e04e35ee-ac5e-4854-b900-73024df9e0a1)
Fixed. Please retest.

**Comment by LarisaM16** [comment]
all good!
